dbt_demo:
  outputs:
    dev:
      account: ummpvlh-in57307
      database: RAW
      password: dbtPassword123
      role: TRANSFORM
      schema: AIRBNB
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
